# Generated by Django 5.1.1 on 2024-10-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_alter_candidate_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('applying_for', models.CharField(max_length=100)),
                ('current_company', models.CharField(blank=True, max_length=100)),
                ('current_location', models.CharField(blank=True, max_length=100)),
                ('experience', models.CharField(max_length=10)),
                ('interview_date', models.DateTimeField()),
                ('interviewer_name', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
