# Generated by Django 5.1.1 on 2024-10-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_interviewapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewapplication',
            name='resume',
            field=models.CharField(max_length=50),
        ),
    ]
