# Generated by Django 5.1.1 on 2024-10-07 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_alter_interviewapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewapplication',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_applications', to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='interviewapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
