# Generated by Django 5.1.1 on 2024-10-08 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_interviewapplication_candidate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('application_received', 'Application Received'), ('hr_interview', 'HR Interview'), ('technical_interview', 'Technical Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='application_received', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='candidates.interviewapplication')),
            ],
        ),
    ]
