# Generated by Django 5.1.1 on 2024-10-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_progressstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewapplication',
            name='applying_for',
        ),
        migrations.RemoveField(
            model_name='interviewapplication',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='interviewapplication',
            name='current_company',
        ),
        migrations.RemoveField(
            model_name='interviewapplication',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='interviewapplication',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='interviewapplication',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='interviewapplication',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='interviewapplication',
            name='last_name',
        ),
        migrations.AddField(
            model_name='interviewapplication',
            name='interviewemail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='interviewapplication',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interviewapplication',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewapplication',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interviewapplication',
            name='interviewer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interviewapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='interviewapplication',
            name='resume',
            field=models.URLField(blank=True, null=True),
        ),
    ]
