# Generated by Django 5.1.1 on 2024-10-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_remove_interviewapplication_applying_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressstatus',
            name='next_round',
            field=models.CharField(blank=True, choices=[('hr_interview', 'HR Interview'), ('assessment', 'Assessment'), ('technical_interview', 'Technical Interview')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='progressstatus',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progressstatus',
            name='status',
            field=models.CharField(choices=[('application_received', 'Application Received'), ('move_to_next_round', 'Move To Next Round'), ('selected', 'Selected'), ('rejected', 'Rejected')], max_length=50),
        ),
    ]
